apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quaility-trace.fullname" . }}
  labels:
    {{- include "quaility-trace.labels" . | nindent 4 }}
data:
  clickhouseConnUrl: {{ .Values.clickhouse.url }}?username={{ .Values.clickhouse.username }}&password={{ .Values.clickhouse.password }}
