apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/sheril5/quality-trace:~1.1
    argocd-image-updater.argoproj.io/ghcr.io/sheril5/quality-trace.update-strategy: semver
    argocd-image-updater.argoproj.io/git-branch: main

spec:
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: charts/quality-trace
    repoURL: https://github.com/Sheril5/quality-trace.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true


