apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
  argocd-image-updater.argoproj.io/image-list: ghcr.io/sheril5/quality-trace
  argocd-image-updater.argoproj.io/myapp-argo-application.update-strategy: semver:1.1.x
  argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/gitcreds
  argocd-image-updater.argoproj.io/git-branch: main

spec:
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: charts/quality-trace
    repoURL: https://github.com/Sheril5/quality-trace.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true


