name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'
env:
    TAGS: 1.0.${{ github.run_number }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/sheril5/quality-trace
    
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: sheril5
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          images: ${{ steps.docker_meta.outputs.images }}
          tags: ghcr.io/sheril/quality-trace/${{ env.TAGS }}
          labels: ${{ steps.docker_meta.outputs.labels }}
