name: Docker Image CI

on:
  push:
    paths-ignore:
      - 'charts/**'
      - '**.md'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'helm/**'
      - '**.md'
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  MAJOR: 1
  MINOR: 2

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/quality-trace:${{ env.MAJOR }}.${{ env.MINOR }}
    - name: Docker push
      run: |
        docker login ${{ env.REGISTRY }} -u jebinjeb -p ${{ secrets.GITHUB_TOKEN }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/quality-trace:${{ env.MAJOR }}.${{ env.MINOR }}
      if: github.event_name == 'push'
    -
      name: Update Minor version
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'MINOR'
        value: $((${{ env.MINOR }}+1))
        repository: ${{ env.IMAGE_NAME }}/quality-trace
        token: ${{ secrets.GITHUB_TOKEN }}

