name: Docker Image CI

on:
  push:
    paths-ignore:
      - 'charts/**'
      - '**.md'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'helm/**'
      - '**.md'
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: sheril5/quality-trace
  MAJOR: 1
  MINOR: 0
  PATCH: 1
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}
    - name: Docker push
      run: |
        docker login ${{ env.REGISTRY }} -u sheril5 -p ${{ secrets.GITHUB_TOKEN }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}
      if: github.event_name == 'push'
    - name: Autoincrement a new patch version
      run: |
         echo "NEW_PATCH_VERSION=$((${{ env.PATCH_VERSION }}+1))" >> $GITHUB_ENV
    - name: Update patch version
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'PATCH_VERSION'
        value: ${{ env.NEW_PATCH_VERSION }}
        repository: ${{ env.IMAGE_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
