name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'
env:
    REGISTRY: ghcr.io
    IMAGES: sheril5/quality-trace
    TAGS: 1.0.${{ github.run_number }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
     contents: read
     packages: write
     
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGES }}
    
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }} 
          images: ${{ env.REGISTRY }}/${{ env.IMAGES }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGES }}:${{ env.TAGS }} 
          labels: ${{ steps.docker_meta.outputs.labels }}
          
