name: Docker Image CI

on:
  push:
    paths-ignore:
      - 'charts/**'
      - '**.md'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'helm/**'
      - '**.md'
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: sheril5/quality-trace
  MAJOR: 1
  MINOR: 0
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update patch
      if: env.MAJOR !=0
      run: |
        PATCH=1
        while true; do
        if [[ "$PATCH" -gt 3 ]]; then
           exit 1 
        fi
        echo PATCH = $PATCH
        ((PATCH++))
        done
        echo "PATCH = $PATCH" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}
    - name: Docker push
      run: |
        docker login ${{ env.REGISTRY }} -u sheril5 -p ${{ secrets.GITHUB_TOKEN }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}
      if: github.event_name == 'push'
